---
title: "Statistical Rethinking Workbook"
author: "Dr. Kim Y. Somfleth"
abstract: "Working through the lectures provided by Richard McElreath, the 2022 version of Statistical Rethinking."
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::pdf_document2: 
    template: "bookdown_templates/template.latex"
    keep_tex: true
    number_sections: false
bibliography: "statistical_rethinking.bib"
biblio-style: "bookdown_templates/bst/hunsrtnat.bst"
link-citations: yes
colorlinks: true
params:
  chapters: all
---

```{r include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo=TRUE)

library(ggplot2)
library(ggthemes)
library(rethinking, quietly=TRUE)
library(gtools)
library(tidyverse)
```

```{r introduction, child = if(params$chapters == 'all') 'lectures/introduction.Rmd' }
```

```{r lecture01, child = if(params$chapters == 'all') 'lectures/lecture01.Rmd' }
```

```{r lecture02, child = if(params$chapters == 'all') 'lectures/lecture02.Rmd' }
```

```{r lecture03, child = if(params$chapters == 'all') 'lectures/lecture03.Rmd' }
```

```{r lecture04, child = if(params$chapters == 'all') 'lectures/lecture04.Rmd' }
```

```{r lecture05, child = if(params$chapters == 'all') 'lectures/lecture05.Rmd' }
```

```{r lecture06, child = if(params$chapters == 'all') 'lectures/lecture06.Rmd' }
```

```{r lecture07, child = if(params$chapters == 'all') 'lectures/lecture07.Rmd' }
```

```{r lecture08, child = if(params$chapters == 'all') 'lectures/lecture08.Rmd' }
```

```{r lecture09, child = if(params$chapters == 'all') 'lectures/lecture09.Rmd' }
```

```{r lecture10, child = if(params$chapters == 'all') 'lectures/lecture10.Rmd' }
```

```{r lecture11, child = if(params$chapters == 'all') 'lectures/lecture11.Rmd' }
```

```{r lecture12, child = if(params$chapters == 'all') 'lectures/lecture12.Rmd' }
```

```{r lecture13, child = if(params$chapters == 'all') 'lectures/lecture13.Rmd' }
```

```{r lecture14, child = if(params$chapters == 'all') 'lectures/lecture14.Rmd' }
```

```{r chapter, child = if(params$chapters != 'all') params$chapters }
```

```{r session}
sessionInfo()
```

# References
